"""initial_mysql

Revision ID: 3692b80d76f5
Revises: 
Create Date: 2026-05-15 19:37:11.982117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3692b80d76f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('agent_config', sa.JSON(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('first_message', sa.Text(), nullable=True),
    sa.Column('functions', sa.JSON(), nullable=True),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('banner_image', sa.String(length=500), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_organization', sa.String(length=255), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('install_count', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('customizable_fields', sa.JSON(), nullable=True),
    sa.Column('required_integrations', sa.JSON(), nullable=True),
    sa.Column('setup_guide', sa.Text(), nullable=True),
    sa.Column('use_cases', sa.JSON(), nullable=True),
    sa.Column('demo_url', sa.String(length=500), nullable=True),
    sa.Column('template_metadata', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_agent_template_category', 'agent_templates', ['category'], unique=False)
    op.create_index('idx_agent_template_featured', 'agent_templates', ['is_featured'], unique=False)
    op.create_index('idx_agent_template_slug', 'agent_templates', ['slug'], unique=False)
    op.create_index('idx_agent_template_status', 'agent_templates', ['status'], unique=False)
    op.create_table('integration_connectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('api_version', sa.String(length=50), nullable=True),
    sa.Column('auth_type', sa.String(length=50), nullable=False),
    sa.Column('auth_config', sa.JSON(), nullable=False),
    sa.Column('supports_triggers', sa.Boolean(), nullable=False),
    sa.Column('supports_actions', sa.Boolean(), nullable=False),
    sa.Column('supports_realtime', sa.Boolean(), nullable=False),
    sa.Column('supports_webhooks', sa.Boolean(), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_hour', sa.Integer(), nullable=True),
    sa.Column('rate_limit_per_day', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_beta', sa.Boolean(), nullable=False),
    sa.Column('is_premium', sa.Boolean(), nullable=False),
    sa.Column('documentation_url', sa.Text(), nullable=True),
    sa.Column('setup_instructions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_connectors_slug'), 'integration_connectors', ['slug'], unique=True)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('stripe_product_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=False),
    sa.Column('price_monthly', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_yearly', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('included_minutes', sa.Integer(), nullable=False),
    sa.Column('included_calls', sa.Integer(), nullable=False),
    sa.Column('max_agents', sa.Integer(), nullable=False),
    sa.Column('max_phone_numbers', sa.Integer(), nullable=False),
    sa.Column('max_knowledge_bases', sa.Integer(), nullable=False),
    sa.Column('overage_rate_per_minute', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('overage_rate_per_call', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_price_id'),
    sa.UniqueConstraint('stripe_product_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('workflow_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('workflow_definition', sa.JSON(), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=False),
    sa.Column('icon', sa.String(length=500), nullable=True),
    sa.Column('banner_image', sa.String(length=500), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_organization', sa.String(length=255), nullable=True),
    sa.Column('is_official', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_free', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('install_count', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('required_integrations', sa.JSON(), nullable=True),
    sa.Column('compatible_agents', sa.JSON(), nullable=True),
    sa.Column('setup_guide', sa.Text(), nullable=True),
    sa.Column('use_cases', sa.JSON(), nullable=True),
    sa.Column('template_metadata', sa.JSON(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_workflow_template_category', 'workflow_templates', ['category'], unique=False)
    op.create_index('idx_workflow_template_slug', 'workflow_templates', ['slug'], unique=False)
    op.create_index('idx_workflow_template_status', 'workflow_templates', ['status'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('plan_type', sa.String(length=50), nullable=False),
    sa.Column('billing_email', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('template_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_template_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_template_id', sa.Uuid(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('is_breaking_change', sa.Boolean(), nullable=False),
    sa.Column('migration_guide', sa.Text(), nullable=True),
    sa.Column('released_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_template_id'], ['agent_templates.id'], ),
    sa.ForeignKeyConstraint(['workflow_template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_version_agent', 'template_versions', ['agent_template_id'], unique=False)
    op.create_index('idx_version_workflow', 'template_versions', ['workflow_template_id'], unique=False)
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('first_message', sa.Text(), nullable=True),
    sa.Column('llm_provider', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('llm_temperature', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('llm_max_tokens', sa.Integer(), nullable=False),
    sa.Column('llm_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('tts_provider', sa.String(length=50), nullable=False),
    sa.Column('tts_voice_id', sa.String(length=255), nullable=True),
    sa.Column('tts_speed', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('tts_pitch', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('tts_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('stt_provider', sa.String(length=50), nullable=False),
    sa.Column('stt_language', sa.String(length=10), nullable=False),
    sa.Column('stt_model', sa.String(length=100), nullable=True),
    sa.Column('stt_api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('interrupt_enabled', sa.Boolean(), nullable=False),
    sa.Column('interrupt_sensitivity', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('silence_timeout', sa.Integer(), nullable=False),
    sa.Column('max_call_duration', sa.Integer(), nullable=False),
    sa.Column('end_call_phrases', sa.JSON(), nullable=False),
    sa.Column('sentiment_analysis_enabled', sa.Boolean(), nullable=False),
    sa.Column('emotion_detection_enabled', sa.Boolean(), nullable=False),
    sa.Column('background_noise_reduction', sa.Boolean(), nullable=False),
    sa.Column('knowledge_base_enabled', sa.Boolean(), nullable=False),
    sa.Column('knowledge_base_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('daily_summaries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('total_call_minutes', sa.Integer(), nullable=False),
    sa.Column('total_call_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('active_agents_count', sa.Integer(), nullable=False),
    sa.Column('total_agent_interactions', sa.Integer(), nullable=False),
    sa.Column('avg_agent_performance', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active_integrations_count', sa.Integer(), nullable=False),
    sa.Column('total_workflow_executions', sa.Integer(), nullable=False),
    sa.Column('avg_integration_health', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('avg_user_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('call_success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('workflow_success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('top_agents', sa.JSON(), nullable=False),
    sa.Column('top_integrations', sa.JSON(), nullable=False),
    sa.Column('call_volume_change', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cost_change', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sentiment_change', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('summary_date')
    )
    op.create_index('idx_daily_summary_org_date', 'daily_summaries', ['organization_id', 'summary_date'], unique=False)
    op.create_table('integration_connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('connector_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('auth_data_encrypted', sa.Text(), nullable=True),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('integration_metadata', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['integration_connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_connections_connector_id'), 'integration_connections', ['connector_id'], unique=False)
    op.create_index(op.f('ix_integration_connections_status'), 'integration_connections', ['status'], unique=False)
    op.create_index(op.f('ix_integration_connections_user_id'), 'integration_connections', ['user_id'], unique=False)
    op.create_table('knowledge_bases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('chunk_size', sa.Integer(), nullable=False),
    sa.Column('chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('vector_dimension', sa.Integer(), nullable=False),
    sa.Column('vector_store_type', sa.String(length=50), nullable=False),
    sa.Column('vector_store_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_kb_active', 'knowledge_bases', ['is_active'], unique=False)
    op.create_index('idx_kb_org', 'knowledge_bases', ['organization_id'], unique=False)
    op.create_table('metrics_cache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_cache_expires', 'metrics_cache', ['expires_at'], unique=False)
    op.create_index('idx_metrics_cache_org_key', 'metrics_cache', ['organization_id', 'cache_key'], unique=False)
    op.create_table('organization_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('invited_by', sa.Uuid(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('realtime_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('current_active_calls', sa.Integer(), nullable=False),
    sa.Column('calls_today', sa.Integer(), nullable=False),
    sa.Column('calls_last_hour', sa.Integer(), nullable=False),
    sa.Column('calls_last_5_minutes', sa.Integer(), nullable=False),
    sa.Column('cost_today', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('cost_last_hour', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('avg_response_time_last_hour', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('current_system_load', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('active_agents', sa.Integer(), nullable=False),
    sa.Column('active_integrations', sa.Integer(), nullable=False),
    sa.Column('active_workflows', sa.Integer(), nullable=False),
    sa.Column('system_health', sa.String(length=20), nullable=False),
    sa.Column('error_rate_last_hour', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('recent_calls', sa.JSON(), nullable=False),
    sa.Column('recent_errors', sa.JSON(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_realtime_metrics_org', 'realtime_metrics', ['organization_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('billing_period', sa.String(length=20), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('current_period_minutes', sa.Integer(), nullable=False),
    sa.Column('current_period_calls', sa.Integer(), nullable=False),
    sa.Column('stripe_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id')
    )
    op.create_index('idx_subscription_org', 'subscriptions', ['organization_id'], unique=False)
    op.create_index('idx_subscription_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscription_stripe', 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_table('template_reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('agent_template_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_template_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('verified_installation', sa.Boolean(), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('moderation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_template_id'], ['agent_templates.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_review_agent', 'template_reviews', ['agent_template_id'], unique=False)
    op.create_index('idx_review_approved', 'template_reviews', ['is_approved'], unique=False)
    op.create_index('idx_review_user', 'template_reviews', ['user_id'], unique=False)
    op.create_index('idx_review_workflow', 'template_reviews', ['workflow_template_id'], unique=False)
    op.create_table('workflows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=False),
    sa.Column('workflow_steps', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('execution_mode', sa.String(length=50), nullable=False),
    sa.Column('error_handling', sa.String(length=50), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('retry_delay', sa.Integer(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflows_is_active'), 'workflows', ['is_active'], unique=False)
    op.create_index(op.f('ix_workflows_organization_id'), 'workflows', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workflows_trigger_type'), 'workflows', ['trigger_type'], unique=False)
    op.create_index(op.f('ix_workflows_user_id'), 'workflows', ['user_id'], unique=False)
    op.create_table('agent_flows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('flow_data', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_functions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('headers', sa.JSON(), nullable=False),
    sa.Column('timeout', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_knowledge_bases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('max_results', sa.Integer(), nullable=False),
    sa.Column('min_similarity', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_inject', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_akb_agent', 'agent_knowledge_bases', ['agent_id'], unique=False)
    op.create_index('idx_akb_kb', 'agent_knowledge_bases', ['knowledge_base_id'], unique=False)
    op.create_index('idx_akb_priority', 'agent_knowledge_bases', ['agent_id', 'priority'], unique=False)
    op.create_table('agent_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('granularity', sa.String(length=20), nullable=False),
    sa.Column('total_interactions', sa.Integer(), nullable=False),
    sa.Column('successful_interactions', sa.Integer(), nullable=False),
    sa.Column('failed_interactions', sa.Integer(), nullable=False),
    sa.Column('avg_response_time', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('avg_confidence_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_function_calls', sa.Integer(), nullable=False),
    sa.Column('successful_function_calls', sa.Integer(), nullable=False),
    sa.Column('failed_function_calls', sa.Integer(), nullable=False),
    sa.Column('function_success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('positive_sentiment_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_user_rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_ratings', sa.Integer(), nullable=False),
    sa.Column('cost_per_interaction', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_metrics_agent_date', 'agent_metrics', ['agent_id', 'metric_date'], unique=False)
    op.create_index('idx_agent_metrics_org_date', 'agent_metrics', ['organization_id', 'metric_date'], unique=False)
    op.create_table('call_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_hour', sa.Integer(), nullable=True),
    sa.Column('granularity', sa.String(length=20), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('completed_calls', sa.Integer(), nullable=False),
    sa.Column('failed_calls', sa.Integer(), nullable=False),
    sa.Column('missed_calls', sa.Integer(), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=False),
    sa.Column('avg_duration', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_duration', sa.Integer(), nullable=True),
    sa.Column('min_duration', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('avg_cost_per_call', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('avg_sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('positive_sentiment_count', sa.Integer(), nullable=False),
    sa.Column('negative_sentiment_count', sa.Integer(), nullable=False),
    sa.Column('neutral_sentiment_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_call_metrics_agent_date', 'call_metrics', ['agent_id', 'metric_date'], unique=False)
    op.create_index('idx_call_metrics_granularity', 'call_metrics', ['granularity', 'metric_date'], unique=False)
    op.create_index('idx_call_metrics_org_date', 'call_metrics', ['organization_id', 'metric_date'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('file_type', sa.String(length=50), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('document_metadata', sa.JSON(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_doc_hash', 'documents', ['content_hash'], unique=False)
    op.create_index('idx_doc_kb', 'documents', ['knowledge_base_id'], unique=False)
    op.create_index('idx_doc_status', 'documents', ['processing_status'], unique=False)
    op.create_table('integration_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('request_headers', sa.JSON(), nullable=True),
    sa.Column('request_body', sa.JSON(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['integration_connections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_logs_connection_id'), 'integration_logs', ['connection_id'], unique=False)
    op.create_index(op.f('ix_integration_logs_created_at'), 'integration_logs', ['created_at'], unique=False)
    op.create_table('integration_metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('integration_id', sa.Uuid(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('granularity', sa.String(length=20), nullable=False),
    sa.Column('total_workflows_executed', sa.Integer(), nullable=False),
    sa.Column('successful_workflows', sa.Integer(), nullable=False),
    sa.Column('failed_workflows', sa.Integer(), nullable=False),
    sa.Column('workflow_success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('total_api_calls', sa.Integer(), nullable=False),
    sa.Column('successful_api_calls', sa.Integer(), nullable=False),
    sa.Column('failed_api_calls', sa.Integer(), nullable=False),
    sa.Column('api_success_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('avg_response_time', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_response_time', sa.Integer(), nullable=True),
    sa.Column('min_response_time', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('timeout_count', sa.Integer(), nullable=False),
    sa.Column('rate_limit_count', sa.Integer(), nullable=False),
    sa.Column('health_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('data_synced_count', sa.Integer(), nullable=False),
    sa.Column('data_sync_errors', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['integration_id'], ['integration_connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_integration_metrics_integration_date', 'integration_metrics', ['integration_id', 'metric_date'], unique=False)
    op.create_index('idx_integration_metrics_org_date', 'integration_metrics', ['organization_id', 'metric_date'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_remaining', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('invoice_pdf', sa.String(length=500), nullable=True),
    sa.Column('hosted_invoice_url', sa.String(length=500), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('charge_id', sa.String(length=255), nullable=True),
    sa.Column('line_items', sa.JSON(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('attempted', sa.Boolean(), nullable=False),
    sa.Column('next_payment_attempt', sa.DateTime(), nullable=True),
    sa.Column('stripe_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_invoice_id')
    )
    op.create_index('idx_invoice_org', 'invoices', ['organization_id'], unique=False)
    op.create_index('idx_invoice_status', 'invoices', ['status'], unique=False)
    op.create_index('idx_invoice_stripe', 'invoices', ['stripe_invoice_id'], unique=False)
    op.create_index('idx_invoice_subscription', 'invoices', ['subscription_id'], unique=False)
    op.create_table('knowledge_base_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('document_metadata', sa.JSON(), nullable=False),
    sa.Column('embedding_vector', sa.Text(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('parent_document_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_document_id'], ['knowledge_base_documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('phone_numbers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('country_code', sa.String(length=10), nullable=True),
    sa.Column('area_code', sa.String(length=10), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_sid', sa.String(length=255), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('monthly_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('squads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('initial_agent_id', sa.Uuid(), nullable=True),
    sa.Column('transfer_rules', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['initial_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_installations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('agent_template_id', sa.Uuid(), nullable=True),
    sa.Column('workflow_template_id', sa.Uuid(), nullable=True),
    sa.Column('installed_version', sa.String(length=50), nullable=False),
    sa.Column('customizations', sa.JSON(), nullable=True),
    sa.Column('created_agent_id', sa.Uuid(), nullable=True),
    sa.Column('created_workflow_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('uninstalled_at', sa.DateTime(), nullable=True),
    sa.Column('installation_metadata', sa.JSON(), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_template_id'], ['agent_templates.id'], ),
    sa.ForeignKeyConstraint(['created_agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['created_workflow_id'], ['workflows.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['workflow_template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_installation_agent', 'template_installations', ['agent_template_id'], unique=False)
    op.create_index('idx_installation_org', 'template_installations', ['organization_id'], unique=False)
    op.create_index('idx_installation_workflow', 'template_installations', ['workflow_template_id'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('usage_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('stripe_usage_record_id', sa.String(length=255), nullable=True),
    sa.Column('reported_to_stripe', sa.Boolean(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('stripe_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_org', 'usage_records', ['organization_id'], unique=False)
    op.create_index('idx_usage_period', 'usage_records', ['period_start', 'period_end'], unique=False)
    op.create_index('idx_usage_subscription', 'usage_records', ['subscription_id'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('steps_executed', sa.Integer(), nullable=False),
    sa.Column('steps_successful', sa.Integer(), nullable=False),
    sa.Column('steps_failed', sa.Integer(), nullable=False),
    sa.Column('result_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details', sa.JSON(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_executions_started_at'), 'workflow_executions', ['started_at'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_id'), 'workflow_executions', ['workflow_id'], unique=False)
    op.create_table('calls',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('squad_id', sa.Uuid(), nullable=True),
    sa.Column('phone_number_id', sa.Uuid(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('from_number', sa.String(length=50), nullable=False),
    sa.Column('to_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('answered_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('billable_duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('recording_duration', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('transcript_json', sa.JSON(), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('emotions', sa.JSON(), nullable=True),
    sa.Column('intent', sa.String(length=255), nullable=True),
    sa.Column('topics', sa.JSON(), nullable=False),
    sa.Column('cost_stt', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_llm', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_tts', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_telephony', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_total', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('provider_call_sid', sa.String(length=255), nullable=True),
    sa.Column('call_metadata', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['phone_number_id'], ['phone_numbers.id'], ),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_call_sid')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=False),
    sa.Column('end_char', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=255), nullable=True),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('embedding_dimension', sa.Integer(), nullable=False),
    sa.Column('chunk_metadata', sa.JSON(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunk_doc', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_chunk_index', 'document_chunks', ['document_id', 'chunk_index'], unique=False)
    op.create_index('idx_chunk_vector', 'document_chunks', ['vector_id'], unique=False)
    op.create_table('payment_failures',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=False),
    sa.Column('stripe_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_charge_id', sa.String(length=255), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('customer_notified', sa.Boolean(), nullable=False),
    sa.Column('admin_notified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_failure_invoice', 'payment_failures', ['invoice_id'], unique=False)
    op.create_index('idx_payment_failure_resolved', 'payment_failures', ['resolved'], unique=False)
    op.create_table('squad_members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('squad_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('transfer_conditions', sa.JSON(), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['squad_id'], ['squads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('call_id', sa.Uuid(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_call_id'), 'call_logs', ['call_id'], unique=False)
    op.create_index(op.f('ix_call_logs_timestamp'), 'call_logs', ['timestamp'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_base_id', sa.Uuid(), nullable=False),
    sa.Column('agent_id', sa.Uuid(), nullable=True),
    sa.Column('call_id', sa.Uuid(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(length=50), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('top_similarity', sa.Float(), nullable=True),
    sa.Column('avg_similarity', sa.Float(), nullable=True),
    sa.Column('result_chunk_ids', sa.JSON(), nullable=True),
    sa.Column('query_duration_ms', sa.Integer(), nullable=True),
    sa.Column('was_helpful', sa.Boolean(), nullable=True),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['knowledge_base_id'], ['knowledge_bases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_query_agent', 'search_queries', ['agent_id'], unique=False)
    op.create_index('idx_query_call', 'search_queries', ['call_id'], unique=False)
    op.create_index('idx_query_created', 'search_queries', ['created_at'], unique=False)
    op.create_index('idx_query_kb', 'search_queries', ['knowledge_base_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_query_kb', table_name='search_queries')
    op.drop_index('idx_query_created', table_name='search_queries')
    op.drop_index('idx_query_call', table_name='search_queries')
    op.drop_index('idx_query_agent', table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_call_logs_timestamp'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_call_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_table('squad_members')
    op.drop_index('idx_payment_failure_resolved', table_name='payment_failures')
    op.drop_index('idx_payment_failure_invoice', table_name='payment_failures')
    op.drop_table('payment_failures')
    op.drop_index('idx_chunk_vector', table_name='document_chunks')
    op.drop_index('idx_chunk_index', table_name='document_chunks')
    op.drop_index('idx_chunk_doc', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_table('calls')
    op.drop_index(op.f('ix_workflow_executions_workflow_id'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_started_at'), table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index('idx_usage_subscription', table_name='usage_records')
    op.drop_index('idx_usage_period', table_name='usage_records')
    op.drop_index('idx_usage_org', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('idx_installation_workflow', table_name='template_installations')
    op.drop_index('idx_installation_org', table_name='template_installations')
    op.drop_index('idx_installation_agent', table_name='template_installations')
    op.drop_table('template_installations')
    op.drop_table('squads')
    op.drop_table('phone_numbers')
    op.drop_table('knowledge_base_documents')
    op.drop_index('idx_invoice_subscription', table_name='invoices')
    op.drop_index('idx_invoice_stripe', table_name='invoices')
    op.drop_index('idx_invoice_status', table_name='invoices')
    op.drop_index('idx_invoice_org', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index('idx_integration_metrics_org_date', table_name='integration_metrics')
    op.drop_index('idx_integration_metrics_integration_date', table_name='integration_metrics')
    op.drop_table('integration_metrics')
    op.drop_index(op.f('ix_integration_logs_created_at'), table_name='integration_logs')
    op.drop_index(op.f('ix_integration_logs_connection_id'), table_name='integration_logs')
    op.drop_table('integration_logs')
    op.drop_index('idx_doc_status', table_name='documents')
    op.drop_index('idx_doc_kb', table_name='documents')
    op.drop_index('idx_doc_hash', table_name='documents')
    op.drop_table('documents')
    op.drop_index('idx_call_metrics_org_date', table_name='call_metrics')
    op.drop_index('idx_call_metrics_granularity', table_name='call_metrics')
    op.drop_index('idx_call_metrics_agent_date', table_name='call_metrics')
    op.drop_table('call_metrics')
    op.drop_index('idx_agent_metrics_org_date', table_name='agent_metrics')
    op.drop_index('idx_agent_metrics_agent_date', table_name='agent_metrics')
    op.drop_table('agent_metrics')
    op.drop_index('idx_akb_priority', table_name='agent_knowledge_bases')
    op.drop_index('idx_akb_kb', table_name='agent_knowledge_bases')
    op.drop_index('idx_akb_agent', table_name='agent_knowledge_bases')
    op.drop_table('agent_knowledge_bases')
    op.drop_table('agent_functions')
    op.drop_table('agent_flows')
    op.drop_index(op.f('ix_workflows_user_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_trigger_type'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_organization_id'), table_name='workflows')
    op.drop_index(op.f('ix_workflows_is_active'), table_name='workflows')
    op.drop_table('workflows')
    op.drop_index('idx_review_workflow', table_name='template_reviews')
    op.drop_index('idx_review_user', table_name='template_reviews')
    op.drop_index('idx_review_approved', table_name='template_reviews')
    op.drop_index('idx_review_agent', table_name='template_reviews')
    op.drop_table('template_reviews')
    op.drop_index('idx_subscription_stripe', table_name='subscriptions')
    op.drop_index('idx_subscription_status', table_name='subscriptions')
    op.drop_index('idx_subscription_org', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('idx_realtime_metrics_org', table_name='realtime_metrics')
    op.drop_table('realtime_metrics')
    op.drop_table('organization_members')
    op.drop_index('idx_metrics_cache_org_key', table_name='metrics_cache')
    op.drop_index('idx_metrics_cache_expires', table_name='metrics_cache')
    op.drop_table('metrics_cache')
    op.drop_index('idx_kb_org', table_name='knowledge_bases')
    op.drop_index('idx_kb_active', table_name='knowledge_bases')
    op.drop_table('knowledge_bases')
    op.drop_index(op.f('ix_integration_connections_user_id'), table_name='integration_connections')
    op.drop_index(op.f('ix_integration_connections_status'), table_name='integration_connections')
    op.drop_index(op.f('ix_integration_connections_connector_id'), table_name='integration_connections')
    op.drop_table('integration_connections')
    op.drop_index('idx_daily_summary_org_date', table_name='daily_summaries')
    op.drop_table('daily_summaries')
    op.drop_table('api_keys')
    op.drop_table('agents')
    op.drop_index('idx_version_workflow', table_name='template_versions')
    op.drop_index('idx_version_agent', table_name='template_versions')
    op.drop_table('template_versions')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index('idx_workflow_template_status', table_name='workflow_templates')
    op.drop_index('idx_workflow_template_slug', table_name='workflow_templates')
    op.drop_index('idx_workflow_template_category', table_name='workflow_templates')
    op.drop_table('workflow_templates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_integration_connectors_slug'), table_name='integration_connectors')
    op.drop_table('integration_connectors')
    op.drop_index('idx_agent_template_status', table_name='agent_templates')
    op.drop_index('idx_agent_template_slug', table_name='agent_templates')
    op.drop_index('idx_agent_template_featured', table_name='agent_templates')
    op.drop_index('idx_agent_template_category', table_name='agent_templates')
    op.drop_table('agent_templates')
    # ### end Alembic commands ###
