#!/usr/bin/env python3
"""
Refresh the list of real top-level domains used to validate websites.

The onboarding form and the API both refuse a website whose ending is not a
registered TLD ("as.asdfdsf"). They each need the list, so this writes both
copies from IANA's published file and they cannot drift apart:

    python3 scripts/update_tlds.py

New TLDs are rare; running this a couple of times a year is plenty.
"""
import textwrap
import urllib.request
from pathlib import Path

SOURCE = "https://data.iana.org/TLD/tlds-alpha-by-domain.txt"
ROOT = Path(__file__).resolve().parent.parent
PYTHON_OUT = ROOT / "backend/app/core/tlds.py"
TS_OUT = ROOT / "frontend/src/lib/tlds.ts"


def main() -> None:
    with urllib.request.urlopen(SOURCE, timeout=30) as response:
        lines = response.read().decode("ascii").splitlines()

    version = lines[0].lstrip("# ").strip()
    tlds = sorted(line.strip().lower() for line in lines[1:] if line.strip())
    if len(tlds) < 1000:
        raise SystemExit(f"Only {len(tlds)} TLDs in {SOURCE}; refusing to write a truncated list.")

    wrapped = "\n".join(textwrap.wrap(" ".join(tlds), width=96))

    PYTHON_OUT.write_text(
        '"""\n'
        "Every top-level domain in the DNS root zone, as published by IANA.\n\n"
        "Generated by scripts/update_tlds.py; do not edit by hand.\n"
        f"Source: {SOURCE}\n"
        f"{version}\n"
        '"""\n\n'
        f'TLDS = frozenset("""\n{wrapped}\n""".split())\n'
    )
    TS_OUT.write_text(
        "/**\n"
        " * Every top-level domain in the DNS root zone, as published by IANA.\n"
        " *\n"
        " * Generated by scripts/update_tlds.py; do not edit by hand.\n"
        f" * Source: {SOURCE}\n"
        f" * {version}\n"
        " */\n"
        f"export const TLDS: ReadonlySet<string> = new Set(`\n{wrapped}\n`.split(/\\s+/).filter(Boolean))\n"
    )
    print(f"Wrote {len(tlds)} TLDs to {PYTHON_OUT.relative_to(ROOT)} and {TS_OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
